### ISSUE TITLE
parseInt() und parseFloat() Baustein

### ISSUE THREAD

**Issue by Eisbaeeer** [smiling-Jack/CCU-IO.ScriptGUI#33]
Hi Steffen, ich wünsche mir noch 2 Bausteine, um string Variable wandeln zu können.
Gruß Eisbaeeer

**Comment by smiling-Jack** [comment]
Ich drin dran.

**Comment by smiling-Jack** [comment]
Wunsch erfüllt in V0.63.0

**Comment by Eisbaeeer** [comment]
Am 21.06.2014 01:04, schrieb smiling-Jack:
