### ISSUE TITLE
Programmfehler?!

### ISSUE THREAD

**Issue by ccvca** [smiling-Jack/CCU-IO.ScriptGUI#34]
_I hope it's ok, when I write german. If not I can try to translate it to english._

https://github.com/smiling-Jack/CCU-IO.ScriptGUI/blob/master/js/ScriptGUI.js#L2283
Im Vergleich zu den anderen Triggern wird in der Zeile der komplette Inhalt von Compiler.Trigger überschrieben und zudem noch der Inhalt von Compiler.Script angehängt.

Ich konnte zwar noch kein Problem mit diesem Codestück feststellen, da ich nicht herausgefunden habe in welchem Kontext es ausgeführt wird, trotzdem gehe ich an dieser Stelle von einem Flüchtigkeitsfehler aus.

**Comment by smiling-Jack** [comment]
Der Tigger ValNE ist noch ein relikt und kann ganz aus dem Code gelöst werden

**Comment by ccvca** [comment]
Ok, das wusste ich nicht, war mir nur beim durchsehen aufgefallen.
