### ISSUE TITLE
Programmboxen

### ISSUE THREAD

**Issue by SGiersch** [smiling-Jack/CCU-IO.ScriptGUI#39]
Nicht mehr benötigte Programmboxen können nicht gelöscht werden.

**Comment by smiling-Jack** [comment]
Wirklich nicht ? auch wenn du mir der rechten Maustaste auf den Programmboxnamen clickst ?

**Comment by SGiersch** [comment]
Na super, überall habe ich drauf geklickt, nur nicht auf den Namen.
Also Kommando zurück, auf dem Namen einer Box funktioniert alles.
Sorry, für die falsche Meldung.

**Comment by smiling-Jack** [comment]
Ich schreib da mal ne Bemerkung mit in die Quick-Help
